* elisp-koans

** What is elisp-koans?
   
   =elisp-koans= helps you learn [[info:elisp:Introduction][Emacs Lisp]] (elisp) via test-driven development.
   You're provided with suites of tests describing components of the elisp
   syntax and environment. Fixing the tests provides a tutorial of elisp.
   
   These koans are for those learning to code in Emacs Lisp and customize Emacs.

** Usage

   Create a clone of this repository:

   #+BEGIN_SRC sh
     git clone https://github.com/jtmoulia/elisp-koans
   #+END_SRC

   First load [[file:elisp-koans.el][elisp-koans.el]] by opening it in Emacs then running =eval-buffer=.

   Next open up [[file:koans/asserts.el::(elisp-koans/define-test][koans/asserts.el]] and navigate to the first test:

   #+BEGIN_SRC emacs-lisp
     (elisp-koans/define-test
      assert-true
      "t is true.  Replace the blank with a t"
      (elisp-koans/assert-true ___))
   #+END_SRC

   Fix the test by replacing the blank (=___=) with the appropriate value, in
   this case =t= as described in the docstring:

   #+BEGIN_SRC emacs-lisp
     (elisp-koans/assert-true t)
   #+END_SRC

   Once the test is fixed, run all the tests by evaluating =elisp-koans/run=.
   The test results will be inserted into a buffer named
   =*elisp-koans-results*=, and the =assert-true= test should be passing as
   indicated by =DONE=. You're ready to move on to the remaining tests, which
   are organized to provide a tour through Emacs Lisp.
   
** Credits

   =elisp-koans= is adapted from Google's [[https://github.com/google/lisp-koans][Common Lisp Koans]], which was in turn
   inspired by the family of TDD Koans, e.g. [[http://rubykoans.com/][Ruby Koans]] and [[https://github.com/gregmalcolm/python_koans][Python Koans]].

** License
   
   The Common Lisp Koan's were modified under the terms of the Apache License.

   =elisp-koans= uses the [[file:LICENSE][Apache License]].
   

